defaults:
  - base_cv
  - hydra/logging
  - model: ??? # Add models or ensembles
  - wandb: train

raw_path: data/shrunken
processed_path: data/processed

scorer:
  _target_: ??? # Add scorer
splitter:
  _target_: src.splitter.bb_splitter.BBSplitter
  n_splits: 5
allow_multiple_instances: true
save_folds: true
