defaults:
  - base_train
  - hydra/logging
  - model: cnn1d
  - wandb: train

data_path: data/shrunken
processed_path: data/processed

scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP
splitter:
  _target_: src.splitter.bb_stratified_splitter.BBStratifiedSplitter
  n_splits: 5
val_split: True
sample_size: 10_000
sample_split: 0.015
allow_multiple_instances: true
