defaults:
  - base_train
  - hydra/logging
  - model: pseudo_cnn1d
  - wandb: train

# Paths
data_path: data/shrunken
cache_path: data/cache

# Scoring
scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP

# Splitting
splitter:
  # _target_: src.splitter.stratified_splitter.StratifiedSplitter
  # n_splits: 5
  _target_: src.splitter.bb_stratified_splitter.BBStratifiedSplitter
  n_splits: 5
  test_size: 0.2

pseudo_label: 'local'
sample_size: 500_000
sample_split: 0.015

allow_multiple_instances: true
