defaults:
  - base_train
  - hydra/logging
  - model: LLM/cnn1d_tokenize_undersample
  - wandb: train

# Paths
data_path: data/shrunken
train_file_name: train.parquet
cache_path: data/cache

# Scoring
scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP
filter_protein: HSA

# Sampling
sample_size: 100_000_000
sample_split: -1

# Splitting
splitter:
   _target_: src.splitter.stratified_splitter.StratifiedSplitter
   n_splits: 5
#  _target_: src.splitter.bb_stratified_splitter.BBStratifiedSplitter
#  n_splits: 5
#  test_size: 0.2

# Data additions
pseudo_label: 'none'
submission_path: 'data/submissions/submission_457.csv'
pseudo_binding_ratio: 0.02 # sweep
pseudo_confidence_threshold: 0.9 # sweep
seh_binding_dataset: false

allow_multiple_instances: true
