defaults:
  - base_train
  - hydra/logging
  - model: cnn1d
  - wandb: train

data_path: data/shrunken
processed_path: data/processed

scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP
splitter:
  _target_: src.splitter.stratified_splitter.StratifiedSplitter
  n_splits: 0
test_size: 0
sample_size: 100_000_000
sample_split: -1 
# val_split: true
allow_multiple_instances: true
