defaults:
  - base_train
  - hydra/logging
  - model: tutorial_notebook
  - wandb: train

data_path: data/shrunken
processed_path: data/processed

scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP
splitter:
  _target_: src.splitter.normal_splitter.NormalSplitter
  n_splits: 5
  protein_level: true
allow_multiple_instances: true
