defaults:
  - base_train
  - hydra/logging
  - model: cnn1d/seh_dataset_test
  - wandb: train

# Paths
data_path: data/shrunken
cache_path: data/cache

# Scoring
scorer:
  _target_: src.scoring.mean_average_precision_scorer.MeanAveragePrecisionScorer
  name: MAP

# Sampling
sample_size: 1_000_000
sample_split: -1

# Splitting
splitter:
  # _target_: src.splitter.stratified_splitter.StratifiedSplitter
  # n_splits: 5
  _target_: src.splitter.bb_stratified_splitter.BBStratifiedSplitter
  n_splits: 5
  test_size: 0.2

# Data additions
pseudo_label: 'none'
submission_path: 'data/submissions/submission_443.csv'
pseudo_binding_ratio: 0.005 # sweep
pseudo_confidence_threshold: 0.895 # sweep
sEH_binding_dataset: true

allow_multiple_instances: true
