defaults:
  - base_train
  - hydra/logging
  - model: test_embeddings # Add models or ensembles
  - wandb: train

data_path: data/shrunken
processed_path: data/processed

scorer:
  _target_: ??? # Add scorer
splitter:
  _target_: src.splitter.bb_splitter.BBSplitter
  n_splits: 5
allow_multiple_instances: true
