defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps: []
y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.graph_trainer.GraphTrainer
      model_name: GCNEdges
      model:
        _target_: src.modules.training.models.gnn_transformer_conv.GNNTransformerModel
        n_classes: 3
        num_node_features: 4
        num_edge_features: 8
      criterion:
        _target_: torch.nn.BCEWithLogitsLoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.AdamW
        lr: 0.005818509475892161
      epochs: 10
      batch_size: 1024
      patience: 3
      dataset:
        _target_: src.modules.training.datasets.graph_dataset.GraphDataset
        retrieval: [ "SMILES_MOL" ]
        steps:
          - _target_: src.modules.training.dataset_steps.graphs.smiles_to_chem_graph.SmilesToChemGraph
          - _target_: src.modules.training.dataset_steps.graphs.graph_augmentations.GraphAugmentationBlock
            p_node_drop: 0.10721099697085149
            p_edge_drop: 0.2144036138680076
            p_edge_mask: 0.1579314980870557
            p_node_mask: 0.2226262149845855
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 63
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 5
        warmup_lr_init: 1e-5
      n_folds: 5
      dataloader_args:
        num_workers: 24
        prefetch_factor: 3
        persistent_workers: false

pred_sys:
  steps:
    - _target_: src.modules.transformation.sigmoid.Sigmoid

label_sys:
  steps: [ ]

