_target_: epochalyst.pipeline.model.model.ModelPipeline
_convert_: partial
x_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Preprocessing pipeline
  steps: []
y_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Label processing pipeline
  steps: []
train_sys:
  _target_: src.modules.training.verbose_training_pipeline.VerboseTrainingPipeline
  steps:
  - _target_: src.modules.training.main_trainer.MainTrainer
    model_name: CNN1D
    model:
      _target_: src.modules.training.models.cnn1d.CNN1D
      n_classes: 3
      num_embeddings: 41
    criterion:
      _target_: torch.nn.BCEWithLogitsLoss
    optimizer:
      _target_: functools.partial
      _args_:
      - _target_: hydra.utils.get_class
        path: torch.optim.Adam
      lr: 0.0018904940035410671
    epochs: 10
    batch_size: 4096
    patience: 5
    dataset:
      _target_: src.modules.training.datasets.main_dataset.MainDataset
      retrieval:
      - SMILES_MOL
      steps:
      - _target_: src.modules.training.dataset_steps.smiles.smiles_randomizer.SmilesRandomizer
        p: 0.059647205237984835
      - _target_: src.modules.training.dataset_steps.smiles.smiles_atom_encoder.SmilesAtomEncoder
        max_enc_size_molecule: 146
      - _target_: src.modules.training.dataset_steps.encodings.atom_augmentation.AtomAugmentation
        p: 0.9777515313864552
    scheduler:
      _target_: functools.partial
      _args_:
      - _target_: hydra.utils.get_class
        path: timm.scheduler.cosine_lr.CosineLRScheduler
      t_initial: 80
      cycle_mul: 1
      cycle_decay: 1
      cycle_limit: 1
      warmup_t: 4
      warmup_lr_init: 2.0e-07
    n_folds: 5
    x_tensor_type: int
    dataloader_args:
      num_workers: 28
      prefetch_factor: 5
      persistent_workers: true
pred_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Postprocessing pipeline
  steps:
  - _target_: src.modules.transformation.sigmoid.Sigmoid
label_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  steps: []
