defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps: 
    - _target_: src.modules.transformation.encoding.simple_full_encoding.SimpleFullEncoding

y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.main_trainer.MainTrainer
      model_name: CNN1D
      model:
        _target_: src.modules.training.models.cnn1d.CNN1D
        n_classes: 3
      criterion:
        _target_: torch.nn.BCEWithLogitsLoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.Adam
        lr: 0.001
      epochs: 10
      batch_size: 4096
      patience: 1
      dataset:
        _target_: src.modules.training.datasets.main_dataset.MainDataset
        retrieval: ["ECFP_MOL"]
        steps:
          - _target_: src.modules.training.dataset_steps.encodings.atom_augmentation.AtomAugmentation
            p: 0.5 
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 40
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 1
        warmup_lr_init: 1e-5
      n_folds: 0
      int_type: true

pred_sys:
  steps:
    - _target_: src.modules.transformation.sigmoid.Sigmoid

label_sys:
  steps: []
