defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps:
    - _target_: src.modules.transformation.atom_graph.AtomGraph
      convert_molecule: True
      convert_building_blocks: False

y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.graph_trainer.GraphTrainer
      model_name: GCNEdges
      model:
        _target_: src.modules.training.models.gcn_edge_features.GCNWithEdgeFeatures
        n_classes: 3
        num_node_features: 4
        num_edge_features: 2
      criterion:
        _target_: torch.nn.BCEWithLogitsLoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.AdamW
        lr: 0.001
      epochs: 10
      batch_size: 256
      patience: 3
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 40
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 1
        warmup_lr_init: 1e-5
      n_folds: 5
      # dataloader_args:
      #   num_workers: 8
      #   prefetch_factor: 2
      #   persistent_workers: false

pred_sys:
  steps:
    - _target_: src.modules.transformation.sigmoid.Sigmoid

label_sys:
  steps: []
