defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps:
    - _target_: src.modules.transformation.ecfp.ECFP
      convert_molecules: True
      bits: 512

y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.one_hot_protein.OneHotProtein
    - _target_: src.modules.training.main_trainer.MainTrainer
      model_name: Linear
      model:
        _target_: src.modules.training.models.linear.Linear
        in_channels: 515
        out_channels: 1
      criterion:
        _target_: torch.nn.BCELoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.Adam
        lr: 0.001
      epochs: 20
      batch_size: 128
      patience: 10
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 40
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 1
        warmup_lr_init: 1e-5

pred_sys:
  steps:
    - _target_: src.modules.transformation.example_transformation_block.ExampleTransformationBlock

label_sys:
  steps:
    - _target_: src.modules.transformation.example_transformation_block.ExampleTransformationBlock
