defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps:
    - _target_: src.modules.transformation.blocks_to_image.BlocksToImage
      img_width: 100
      img_heigth: 50

y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.image_trainer.ImageTrainer
      model_name: TIMM
      model:
        _target_: epochalyst.pipeline.model.training.models.timm.Timm
        model_name: efficientnet_b0
        in_channels: 3
        out_channels: 3
      criterion:
        _target_: torch.nn.BCEWithLogitsLoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.Adam
        lr: 0.001
      epochs: 10
      batch_size: 256
      patience: 10
      dataset:
        _target_: src.modules.training.datasets.main_dataset.MainDataset
        retrieval: ["EMBEDDING_BB"]
        steps:
          - _target_: src.modules.training.dataset_steps.images.blocks_to_image.BlocksToImage
            img_width: 100
            img_heigth: 50
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 100
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 1
        warmup_lr_init: 1e-5
      n_folds: 5
      dataloader_args:
        num_workers: 24
        prefetch_factor: 4
        persistent_workers: false


pred_sys:
  steps:
    - _target_: src.modules.transformation.sigmoid.Sigmoid

label_sys:
  steps: []
