defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps: []

y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.image_trainer.ImageTrainer
      model_name: CNN1D_MOL_TOK
      model:
        _target_: src.modules.training.models.bert.Net
        n_classes: 3
        vocab_size: 5000
        hidden_dim: 128
        filters: 64
      criterion:
        _target_: torch.nn.BCEWithLogitsLoss
        # _target_: src.modules.loss.focal_loss.FocalLoss
      optimizer: # Partially instantiate optimizer, so model parameters can be linked at runtime
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: torch.optim.Adam
        lr: 0.001
      epochs: 10
      batch_size: 32
      patience: 2
      dataset:
        _target_: src.modules.training.datasets.main_dataset.MainDataset
        retrieval: ["SMILES_MOL"]
        steps:
          - _target_: src.modules.training.dataset_steps.smiles.tokenize_molecule.TokenizeMolecule
            tokenizer_name: "samples_100M_window_4"
            padding_size: 150
      scheduler:
        _target_: functools.partial
        _args_:
          - _target_: hydra.utils.get_class
            path: timm.scheduler.cosine_lr.CosineLRScheduler
        t_initial: 40
        cycle_mul: 1
        cycle_decay: 1
        cycle_limit: 1
        warmup_t: 1
        warmup_lr_init: 1e-5
      n_folds: 5
      x_tensor_type: int
      dataloader_args:
        num_workers: 8
        prefetch_factor: 5
        persistent_workers: false
    - _target_: src.modules.training.analysis.prediction_statistics.PredictionStatistics

pred_sys:
  steps:
    - _target_: src.modules.transformation.sigmoid.Sigmoid

label_sys:
  steps: []