defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps: []


y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.models.lazy_xgb.LazyXGB
      model_name: "XGBClassifier"
      # Training parameters
      chunk_size: 100000
      queue_size: 5
      num_boost_round: 200
      device: cuda
      # Model parameters
      eval_metric: map
      booster: gbtree
      eta: 0.1
      max_depth: 6
      objective: "binary:logistic"
      tree_method: hist


      steps:
        - _target_: src.modules.training.dataset_steps.fingerprints.Fingerprints
          fingerprint:
            _target_: skfp.fingerprints.ECFPFingerprint
            fp_size: 1024
    - _target_: src.modules.training.analysis.prediction_statistics.PredictionStatistics

pred_sys:
  steps: []

label_sys:
  steps: []
