defaults:
  - pipeline/default@_here_
  - _self_

x_sys:
  steps: []


y_sys:
  steps: []

train_sys:
  steps:
    - _target_: src.modules.training.models.lazy_xgb.LazyXGB
      model_name: "XGBClassifier"
      chunk_size: 50000
      steps:
        - _target_: src.modules.training.dataset_steps.fingerprints.Fingerprints
          fingerprint:
            _target_: skfp.fingerprints.ECFPFingerprint
            fp_size: 512
    - _target_: src.modules.training.analysis.prediction_statistics.PredictionStatistics

pred_sys:
  steps: []

label_sys:
  steps: []
